name: Build Game APK

on:
  push:
    branches: [ "main" ]

jobs:
  build-android:
    runs-on: ubuntu-latest
    steps:
    - name: Ambil File dari GitHub
      uses: actions/checkout@v4

    - name: Siapkan Mesin Node
      uses: actions/setup-node@v4
      with:
        node-version: '18'

    - name: Siapkan Mesin Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Install Alat Tukang
      run: npm install -g cordova

    - name: Merakit APK Android
      run: |
        cordova create game com.banggo.mosquito "MosquitoInvasion"
        rm -rf game/www/*
        cp -r www/* game/www/
        cp config.xml game/config.xml
        cd game
        cordova platform add android
        cordova build android --release

    - name: Kirim APK ke Bosku!
      uses: actions/upload-artifact@v4
      with:
        name: Mosquito-Invasion-APK
        path: '**/*.apk'
