name: Build Game APK

on:
  push:
    branches: [ "main" ]

jobs:
  build-android:
    runs-on: ubuntu-latest
    steps:
    - name: Ambil File
      uses: actions/checkout@v4

    - name: Siapkan Mesin Node
      uses: actions/setup-node@v4
      with:
        node-version: '18'

    - name: Siapkan Mesin Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Install Cordova
      run: npm install -g cordova

    - name: Merakit APK Android (Mode Developer)
      run: |
        cordova create game com.banggo.mosquito "MosquitoInvasion"
        
        # Pindahkan kodemu
        if [ -d "www" ]; then
          cp -r www/* game/www/
        else
          cp index.html game/www/
          cp -r assets game/www/
        fi
        
        cp config.xml game/config.xml
        cd game
        cordova platform add android
        
        # Bikin APK-nya
        cordova build android

    - name: Kirim APK ke Bosku!
      uses: actions/upload-artifact@v4
      with:
        name: Mosquito-Invasion-APK
        # Tembak langsung ke alamat pasti file-nya berada!
        path: game/platforms/android/app/build/outputs/apk/debug/app-debug.apk
